// Generated by Wrangler by running `wrangler types`

interface Env {
	B2_APP_ID: string;
	B2_APP_KEY: string;
	B2_BUCKET_ID: string;
	DOWNLOAD_BASE_URL: string;
	JWT_SECRET: string;
	USERNAME: string;
	PASSWORD: string;
	DB: D1Database;
}
