name = "b2-browser"
main = "src/index.tsx"
compatibility_date = "2024-12-18"

[observability]
enabled = true

[assets]
directory = "public"

[[d1_databases]]
binding = "DB"
database_name = "b2-browser"
database_id = "5fe5906e-e8fd-4980-b146-9779ac448f74"
